### ISSUE TITLE
Correctness of the British English example

### ISSUE THREAD

**Issue by michael-heerdegen** [tlikonen/wcheck-mode#4]
Hello,

I tried this package today.  I tried the British English example from the README.  It took me quite a while to find out that the example was wrong, at least, for my version of ispell.  The "args" must include the "-a" option for ispell; else, nothing ever happens.  Should we correct the doc?

While debugging, I got to know a lot of the code, btw - this seems to be a quite cool package!

**Comment by tlikonen** [comment]
Standard ispell uses "-l" option to just list mispelled words.
