### ISSUE TITLE
Problem with apostrophe in Ukrainian

### ISSUE THREAD

**Issue by elandx** [tlikonen/wcheck-mode#7]
Thank You for wcheck-mode! It works great, but in Ukrainian all words with apostrophe are marked as errors. enchant/hunspell from command line accept those words as correct.

**Comment by tlikonen** [comment]
I had missed this open issue. Sorry!

From Wcheck's side you can configure wcheck-language-data and its regexp-start, regexp-body, regexp-end, regexp-discard and syntax (table). With those options you can choose what strings are sent to your external program.

**Comment by elandx** [comment]
Thank you very much for your answer. 
Sorry, I forgot about this problem. I did as you advised, changed the `regexp-body` from `\w+?` to `\w+` and now everything works. 
Thanks again.
